// packages/react/src/App.tsx
import { useState } from 'react'
import { useHistory } from './hooks/use-history'
import './App.css'

function App() {
  const { execute, canUndo, canRedo, undo, redo } = useHistory({ size: 100, coalesce: true })

  const [numbs, setNumbs] = useState(0)
  const [color, setColor] = useState('#ffffff')

  function addNumb() {
    execute({
      do: () => setNumbs(prev => prev + 1),
      undo: () => setNumbs(prev => prev - 1)
    })
  }

  function subNumb() {
    execute({
      do: () => setNumbs(prev => prev - 1),
      undo: () => setNumbs(prev => prev + 1)
    })
  }

  function changeColor(e: React.ChangeEvent<HTMLInputElement>) {
    const oldValue = color
    const newValue = e.target.value

    execute({
      key: 'color-change',
      do: () => setColor(newValue),
      undo: () => setColor(oldValue),
    })
  }

  return (
    <>
      <div>
        <div>
          <p>Can undo: {canUndo ? 'y' : 'n'}</p>
          <p>Can redo: {canRedo ? 'y' : 'n'}</p>
        </div>
        <button onClick={addNumb}>+</button>
        <button onClick={subNumb}>-</button>
        <button>{numbs}</button>
      </div>

      <div>
        <button onClick={undo} disabled={!canUndo}>Undo</button>
        <button onClick={redo} disabled={!canRedo}>Redo</button>
      </div>

      <div>
        <input onChange={changeColor} value={color} type="color" id="foreground" name="foreground" />
        <label htmlFor="foreground">Foreground color</label>
      </div>
    </>
  )
}

export default App

// packages/svelte/src/App.svelte
<script lang="ts">
  import { useHistory } from './hooks/use-history.svelte';

  const history = useHistory({ size: 100, coalesce: true });

  let numbs = $state(0);
  let color = $state('#ffffff');

  function addNumb() {
    history.execute({
      do: () => numbs += 1,
      undo: () => numbs -= 1
    });
  }

  function subNumb() {
    history.execute({
      do: () => numbs--,
      undo: () => numbs++
    });
  }

  function changeColor(e: Event) {
    const oldValue = color;
    const newValue = (e.target as HTMLInputElement).value;

    history.execute({
      key: 'color-change',
      do: () => color = newValue,
      undo: () => color = oldValue,
    });
  }
</script>

<div>
  <div>
    <p>Can undo: {history.canUndo ? 'y' : 'n'}</p>
    <p>Can redo: {history.canRedo ? 'y' : 'n'}</p>
  </div>
  <button onclick={addNumb}>+</button>
  <button onclick={subNumb}>-</button>
  <button>{numbs}</button>
</div>

<div>
  <button onclick={history.undo} disabled={!history.canUndo}>Undo</button>
  <button onclick={history.redo} disabled={!history.canRedo}>Redo</button>
</div>

<div>
  <input oninput={changeColor} value={color} type="color" id="foreground" name="foreground" />
  <label for="foreground">Foreground color</label>
</div>

<style>
  button:disabled {
    opacity: 0.4;
  }
</style>
